ci: workaround orphaned QEMU processes blocking host ports
This is a nasty workaround to unblock the CI in some cases. For reasons
unknown to us, our runners sometimes keep running that shut be stopped
already, causing failed nightly scheduled pipeline runs.

This is mostly save as
- we have the `host-tcp-ports` resource group
- we prevent the corresponding pipeline runs in forks
- we pray no one else uses host port 2222 in their CI

On-behalf-of: SAP philipp.schuster@sap.com
Signed-off-by: Philipp Schuster <philipp.schuster@cyberus-technology.de>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -86,5 +86,26 @@ test:nixos-tests:
     paths:
       - logs/
   script:
+    # We experience CI weirdness with our runners: sometimes we see orphaned
+    # QEMU processes still running and blocking host ports 2222 and 3333, thus,
+    # the CI will fail.
+    #
+    # On the long term, we should refactor libvirt-tests to export all tests in
+    # CI mode and interactive mode where only the latter also binds the host
+    # ports. This here, however, is the more pragmatic workaround for now.
+    - |
+      echo "Checking if any orphaned QEMU process needs to be killed ..."
+      
+      kill_qemu() {
+        local port=$1
+        local pid=$(nix shell nixpkgs#procps --command bash -c "pgrep -f 'qemu.*[h]ostfwd=tcp::$port' || echo -1")
+        if [ "${pid}" -gt 1 ]; then
+          nix shell nixpkgs#ansi --command bash -c "echo -e \"\$(ansi red bold)FOUND ORPHANED QEMU (pid=$pid) blocking port $port: Killing to unblock pipeline\$(ansi reset)\"" 
+          kill -KILL "${pid}"
+        fi
+      }
+      
+      kill_qemu 2222
+      kill_qemu 3333
     - mkdir "${DBG_LOG_DIR}"
     - nix run -L .#tests.x86_64-linux.default.driver 2>&1 | tee "${DBG_LOG_DIR}/nixos_driver.log"
